esphome:
  name: watcher

esp32:
 board: lolin32
 framework:
   type: arduino

logger:
  level: INFO

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid_home
  password: !secret wifi_password_home
  fast_connect: true
  ap:
    ssid: "Watcher Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

web_server:
 port: 80

light:
- platform: rgb
  name: "Watcher"
  red: red
  green: green
  blue: blue
  effects:
    - random:
    - pulse:
    - strobe:
    - flicker:

output:
- platform: ledc
  id: red
  pin: GPIO22
  max_power: 100%
- platform: ledc
  id: green
  pin: GPIO1
  max_power: 100%
- platform: ledc
  id: blue
  pin: GPIO3
  max_power: 100%
