esphome:
  name: water-meter-grube

esp32:
  board: lolin32 
  framework:
    type: arduino

logger:
  level: INFO

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  networks:
    - ssid: !secret wifi_ssid_home
      password: !secret wifi_password_home
    - ssid: !secret wifi_ssid_garten
      password: !secret wifi_password_garten
  ap:
    ssid: "WaterMeterGrube Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

web_server:
  port: 80

dallas:
  - pin: 22

sensor:
  - platform: pulse_counter
    pin:
      number: 23
      mode:
        input: true
        pullup: true
#    count_mode:
#      rising_edge: DISABLE
#      falling_edge: INCREMENT
    name: "Water Meter Grube l/h"
    id: water_meter_grube
    update_interval: 200ms
    unit_of_measurement: 'l/h'
    filters:
      - multiply: 0.0625
    total:
      unit_of_measurement: 'l'
      name:  "Water Meter Grube Total Current"
      filters:
        - multiply: 0.25
  - platform: integration
    name: "Water Meter Grube Total Daily"
    id: water_meter_grube_integration
    sensor: water_meter_grube
    time_unit: h
  - platform: dallas
    index: 0
    name: "Water Meter Grube Temperature"

time:
  - platform: sntp
    on_time:
      - cron: '0 0 0 * * *'
        then:
          - sensor.integration.reset: water_meter_grube_integration